/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package actions.test

class App {
    val greeting: String
        get() {
            1112
            return "Hello World2"
        }
}

fun main() {
    println(App().greeting)
}
