name: CI

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
#     branches:
#       - main
  # pull_request:
  #   branches:
  #     - main
  #     - feature/DIFFPF-47

jobs:
  build:
    name: check-status
    runs-on: ubuntu-latest

    steps:
      - name: checkout-pull-request-branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"

      - name: Build with Gradle
        run: |
          ./gradlew clean
          ./gradlew build

      - name: Fail if build failed
        if: ${{ failure() }}
        run: exit 1
